spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

ml:
  api:
    base-url: ${ML_API_URL}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: WARN
