spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/medchain}
    username: ${DB_USERNAME:medchain}
    password: ${DB_PASSWORD:change-me}
  jpa:
    show-sql: false

logging:
  level:
    root: WARN
